# Generated by Django 2.2.5 on 2019-09-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Ciudad', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Tblgenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Genero', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tblpagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Pagina', models.CharField(max_length=35)),
                ('Url_Pagina', models.CharField(max_length=35)),
                ('Correo_Pagina', models.EmailField(max_length=254)),
                ('Contraseña_Pagina', models.CharField(max_length=100)),
                ('Descripcion_Pagina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tbltipodocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Documento', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Tblusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Usuario', models.CharField(max_length=35)),
                ('Apellido_Parterno', models.CharField(max_length=35)),
                ('Apellido_Materno', models.CharField(max_length=35)),
                ('No_Documento', models.CharField(max_length=35)),
                ('Contraseña', models.CharField(max_length=100)),
                ('Correo_Usuario', models.EmailField(max_length=254)),
                ('Fecha_Nacimiento', models.DateTimeField(auto_now_add=True)),
                ('Telefono', models.CharField(max_length=35)),
                ('Direccion_Domicilio', models.CharField(max_length=35)),
                ('Correo_Alterno', models.EmailField(max_length=254)),
            ],
        ),
    ]
