# Generated by Django 2.2.5 on 2019-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario_pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagina', models.BigIntegerField()),
                ('Pagina_Red', models.CharField(choices=[('F', 'Facebook'), ('I', 'Instagram')], default='N/A', max_length=1)),
                ('Pagina_Compra', models.CharField(choices=[('A', 'Amazon'), ('E', 'Ebay')], default='N/A', max_length=35)),
                ('Correo_Cuenta', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
                ('Descripcion_Cuenta', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='listado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField()),
                ('Apellido_Parterno', models.CharField(max_length=35)),
                ('Apellido_Materno', models.CharField(max_length=35)),
                ('Nombre', models.CharField(max_length=35)),
                ('id_pagina', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField()),
                ('correo_activo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recuperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_activo', models.EmailField(max_length=254)),
                ('correo_alternativo', models.EmailField(max_length=254)),
                ('id_usuario', models.BigIntegerField()),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField()),
                ('Apellido_Parterno', models.CharField(max_length=35)),
                ('Apellido_Materno', models.CharField(max_length=35)),
                ('Nombre', models.CharField(max_length=35)),
                ('Telefono', models.IntegerField()),
                ('Direccion_Domicilio', models.CharField(max_length=35)),
                ('correo_activo', models.EmailField(max_length=254)),
                ('correo_alternativo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateTimeField(auto_now_add=True)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Ciudad', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BigIntegerField()),
                ('Apellido_Parterno', models.CharField(max_length=35)),
                ('Apellido_Materno', models.CharField(max_length=35)),
                ('Nombre', models.CharField(max_length=35)),
                ('correo_activo', models.EmailField(max_length=254)),
                ('FechaNacimiento', models.DateTimeField(auto_now_add=True)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Ciudad', models.CharField(max_length=35)),
            ],
        ),
    ]
