# Generated by Django 2.2.5 on 2019-10-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblciudad',
            name='Id_Ciudad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='keymanager.Tblusuario'),
        ),
        migrations.AddField(
            model_name='tblgenero',
            name='Id_Genero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='keymanager.Tblusuario'),
        ),
        migrations.AddField(
            model_name='tblpagina',
            name='Id_Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keymanager.Tblusuario'),
        ),
        migrations.AddField(
            model_name='tbltipodocumento',
            name='Id_Tipo_Documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='keymanager.Tblusuario'),
        ),
    ]
